### PR TITLE
Admin dashboard is added and some controls refs #22

### PR DESCRIPTION
**Pull request by CollinsLord**

### CODE REVIEW

**Comment by lcabrini** [comment]
I just need to know if we are no longer uinsg the HtmlServiceProvider. Because you deleted the line I added to composer.json.

**Comment by CollinsLord** [comment]
Actually i have not deleted any file,i just added what i did to it.

**Comment by lcabrini** [comment]
Ah, I see. then I think you didn't do a:

    git pull upstream master

to get my changes after I had committed and pushed. Hm. OK. Try to do that so that you get the latest updates, then push again and do a pull request.

**Comment by CollinsLord** [comment]
I did that.

**Pull request merged**
